name: Terraform Apply

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

env:
  ACTIONS_STEP_DEBUG: true

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      TF_VAR_gcp_credentials: ${{ secrets.GCP_CREDENTIALS }}
      TF_VAR_project_id: ${{ secrets.GCP_PROJECT_ID }}
      TF_VAR_workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER}}
      TF_VAR_service_account: ${{ secrets.SERVICE_ACCOUNT}}
      TF_VAR_clusterName: ${{ secrets.SERVICE_ACCOUNT}}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: '${{ secrets.WORKLOAD_IDENTITY_PROVIDER}}'
          service_account: '${{ secrets.SERVICE_ACCOUNT}}'

     
      - uses: "google-github-actions/setup-gcloud@v2"
        with:
          install_components: "gke-gcloud-auth-plugin"   

      # - name: Authenticate to GKE cluster
      #   uses: google-github-actions/get-gke-credentials@v2
      #   with:
      #     cluster_name: gke-cluster-admin
      #     location: us-east1-b
  
      - name: Initialize Terraform
        run: terraform init -backend-config="bucket=kube-wordpress-bucket" -backend-config="prefix=kube-wodpress/state" 

      - name: Apply Terraform
        run: terraform apply -var-file=envs/admin.tfvars -auto-approve
