name: Terraform Apply

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

env:
  ACTIONS_STEP_DEBUG: true

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      TF_VAR_gcp_credentials: ${{ secrets.GCP_CREDENTIALS }}
      TF_VAR_project_id: ${{ secrets.GCP_PROJECT_ID }}
      TF_VAR_project_number: ${{ secrets.GCP_PROJECT_NUMBER}}
      TF_VAR_pool_id: ${{ secrets.POOL_ID}}
      TF_VAR_provider_id: ${{ secrets.PROVIDER_ID}}
      TF_VAR_service_account_name: ${{ secrets.SERVICE_ACCOUNT_NAME}}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - name: Print HTTP
        run: |
          curl -v https://httpbin.org/headers

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/${{ secrets.GCP_PROJECT_NUMBER}}/locations/global/workloadIdentityPools/${{secrets.POOL_ID}}/providers/${{ secrets.PROVIDER_ID}}'
          service_account: '${{ secrets.SERVICE_ACCOUNT_NAME}}@${{ secrets.GCP_PROJECT_ID }}.iam.gserviceaccount.com'

     
      - name: Install gke-gcloud-auth-plugin manually
        run: |
          export USE_GKE_GCLOUD_AUTH_PLUGIN=True
          gcloud auth application-default login --quiet    


      - name: Initialize Terraform
        run: terraform init -backend-config="bucket=kube-wordpress-bucket" -backend-config="prefix=kube-wodpress/state" 

      - name: Apply Terraform
        run: terraform apply -var-file=envs/admin.tfvars -auto-approve
