name: Terraform Apply

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      TF_VAR_gcp_credentials: ${{ secrets.GCP_CREDENTIALS }}
      TF_VAR_project_id: ${{ secrets.GCP_PROJECT_ID }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ env.TF_VAR_gcp_credentials }}

      - name: Install gke-gcloud-auth-plugin
        run: |
          sudo apt-get update && sudo apt-get install -y google-cloud-cli-gke-gcloud-auth-plugin

      - name: Initialize Terraform
        run: terraform init -backend-config="bucket=kube-wordpress-bucket" -backend-config="prefix=kube-wodpress/state" 

      - name: Apply Terraform
        run: terraform apply -var-file=envs/admin.tfvars -auto-approve
